helm:
  parameters:
  - name: image.name
    value: ghcr.io/p-nasimonan/vrc-queue-monitor/backend
    forcestring: true
  - name: image.tag
    value: sha-28df0c2
    forcestring: true
  - name: frontend.image.tag
    value: sha-5a57b0b
    forcestring: true
  - name: backendApi.image.tag
    value: sha-28df0c2
    forcestring: true
  - name: backendCollector.image.tag
    value: sha-28df0c2
    forcestring: true
